services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27077:27017"
    volumes:
      - mongo-data:/data/db
  
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6479:6379"

volumes:
  mongo-data:
